services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: altyex
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cashflow-network

volumes:
  mysql_data:

networks:
  cashflow-network:
    driver: bridge